function criarOS(d){
  exigir_(d,['tipo','locacaoId','dataProgramada','motoristaId','caminhaoId']);if(!Array.isArray(d.itemIds)||!d.itemIds.length)throw new Error('Selecione ao menos um item.');validarMotoristaCaminhao_(d.motoristaId,d.caminhaoId);
  const loc=buscarPor_('Locacoes','ID',d.locacaoId);if(!loc)throw new Error('Locação não encontrada.');const id=uuid_(),agora=agora_(),os={ID:id,Numero:'OS-'+Utilities.formatDate(agora,APP.TZ,'yyyyMMdd-HHmmss'),Tipo:d.tipo,LocacaoID:loc.ID,ClienteID:loc.ClienteID,EnderecoSnapshot:loc.EnderecoSnapshot,DataProgramada:parseData_(d.dataProgramada),MotoristaID:d.motoristaId,CaminhaoID:d.caminhaoId,Prioridade:d.prioridade||'Normal',Observacoes:sanitizarTexto_(d.observacoes),Status:APP.OS.PROGRAMADA,Idempotencia:d.idempotencia||uuid_(),CriadoEm:agora,CriadoPor:emailAtual_(),AtualizadoEm:agora};
  if(buscarPor_('OrdensServico','Idempotencia',os.Idempotencia))throw new Error('Esta ordem já foi registrada.');inserir_('OrdensServico',os);
  d.itemIds.forEach(itemId=>{const i=buscarPor_('LocacaoItens','ID',itemId);if(!i||String(i.LocacaoID)!==String(loc.ID))throw new Error('Item inválido.');inserir_('OSItens',{ID:uuid_(),OSID:id,LocacaoItemID:i.ID,CacambaID:i.CacambaID,TipoResiduoID:i.TipoResiduoID});const st=d.tipo==='Entrega'?APP.ITEM.ENTREGA_PROGRAMADA:d.tipo==='Retirada'?APP.ITEM.RETIRADA_PROGRAMADA:i.Status;atualizarPorId_('LocacaoItens',i.ID,{Status:st,AtualizadoEm:agora});});auditar_('CRIAR','OrdensServico',id,null,os);return os;
}
function listarMinhasOS(d){const u=usuarioAtual_();if(u.Perfil!==APP.PERFIS.MOTORISTA)throw new Error('Acesso de motorista necessário.');if(!u.MotoristaID)throw new Error('Usuário sem motorista vinculado.');let lista=tabela_('OrdensServico').filter(x=>String(x.MotoristaID)===String(u.MotoristaID));if(d.status)lista=lista.filter(x=>x.Status===d.status);return lista.sort((a,b)=>new Date(a.DataProgramada)-new Date(b.DataProgramada)).map(os=>Object.assign({},os,{itens:tabela_('OSItens').filter(i=>String(i.OSID)===String(os.ID))}));}
function validarOsDoMotorista_(id){const os=buscarPor_('OrdensServico','ID',id);if(!os)throw new Error('OS não encontrada.');const u=usuarioAtual_();if(u.Perfil===APP.PERFIS.MOTORISTA&&String(u.MotoristaID)!==String(os.MotoristaID))throw new Error('OS não atribuída a você.');return os;}
function iniciarOS(d){const os=validarOsDoMotorista_(d.osId);if(os.Status!==APP.OS.PROGRAMADA)throw new Error('Somente OS programada pode ser iniciada.');const r=atualizarPorId_('OrdensServico',os.ID,{Status:APP.OS.DESLOCAMENTO,InicioEm:agora_(),AtualizadoEm:agora_()});auditar_('INICIAR','OrdensServico',os.ID,r.antes,r.depois);return r.depois;}
function registrarImpedimento(d){const os=validarOsDoMotorista_(d.osId);exigir_(d,['motivo']);const r=atualizarPorId_('OrdensServico',os.ID,{Status:APP.OS.NAO_REALIZADA,MotivoImpedimento:sanitizarTexto_(d.motivo),ConclusaoEm:agora_(),AtualizadoEm:agora_()});auditar_('IMPEDIMENTO','OrdensServico',os.ID,r.antes,r.depois);return r.depois;}
function concluirOS(d){
  const os=validarOsDoMotorista_(d.osId);if([APP.OS.CONCLUIDA,APP.OS.CANCELADA].includes(os.Status))throw new Error('OS já encerrada.');if(!Array.isArray(d.fotos)||d.fotos.length<2)throw new Error('Anexe no mínimo duas fotos.');exigir_(d,['assinaturaBase64','nomeSignatario']);const lock=LockService.getScriptLock();lock.waitLock(30000);
  try{const itens=tabela_('OSItens').filter(i=>String(i.OSID)===String(os.ID));if(!itens.length)throw new Error('OS sem itens.');const arquivos=salvarArquivosOS_(os,d.fotos,d.assinaturaBase64);const agora=agora_();itens.forEach(oi=>{const li=buscarPor_('LocacaoItens','ID',oi.LocacaoItemID);if(os.Tipo==='Entrega'){atualizarPorId_('LocacaoItens',li.ID,{EntregaEfetiva:agora,Status:APP.ITEM.ENTREGUE,MotoristaEntregaID:os.MotoristaID,CaminhaoEntregaID:os.CaminhaoID,AtualizadoEm:agora});movimentarCacamba_(li.CacambaID,li.ID,os.ID,'Entrega',APP.CACAMBA.LOCADA);}else if(os.Tipo==='Retirada'){const loc=buscarPor_('Locacoes','ID',li.LocacaoID),dias=diasExcedentes_(li.EntregaEfetiva,agora,loc.PrazoPadrao),extra=dias*numero_(li.ValorDiaria);atualizarPorId_('LocacaoItens',li.ID,{RetiradaEfetiva:agora,Status:APP.ITEM.RETIRADO,MotoristaRetiradaID:os.MotoristaID,CaminhaoRetiradaID:os.CaminhaoID,DiasExcedentes:dias,ValorAdicional:numero_(li.ValorAdicional)+extra,AtualizadoEm:agora});movimentarCacamba_(li.CacambaID,li.ID,os.ID,'Retirada',d.enviarManutencao?APP.CACAMBA.MANUTENCAO:APP.CACAMBA.DISPONIVEL);}});
    const r=atualizarPorId_('OrdensServico',os.ID,{Status:APP.OS.CONCLUIDA,ConclusaoEm:agora,NomeSignatario:sanitizarTexto_(d.nomeSignatario,120),AssinaturaArquivoID:arquivos.assinaturaId,Observacoes:sanitizarTexto_(d.observacoes),AtualizadoEm:agora});recalcularLocacao_(os.LocacaoID);auditar_('CONCLUIR','OrdensServico',os.ID,r.antes,r.depois);return r.depois;
  }finally{lock.releaseLock();}
}
function recalcularLocacao_(locacaoId){const loc=buscarPor_('Locacoes','ID',locacaoId),it=tabela_('LocacaoItens').filter(i=>String(i.LocacaoID)===String(locacaoId)),fim=it.every(i=>[APP.ITEM.RETIRADO,APP.ITEM.CANCELADO,APP.ITEM.TROCADO].includes(i.Status)),entregues=it.some(i=>i.Status===APP.ITEM.ENTREGUE),extras=it.reduce((s,i)=>s+numero_(i.ValorAdicional),0),total=numero_(loc.ValorTotal)+extras,status=fim?APP.LOCACAO.FINALIZADA:entregues?APP.LOCACAO.ANDAMENTO:loc.StatusOperacional;atualizarPorId_('Locacoes',locacaoId,{StatusOperacional:status,ValorTotal:total,Saldo:Math.max(0,total-numero_(loc.ValorRecebido)),AtualizadoEm:agora_()});}

function salvarArquivosOS_(os,fotos,assinaturaBase64){
  const ano=String(new Date().getFullYear()),base=obterOuCriarPasta_(obterOuCriarPasta_(pastaRaiz_(),'Ordens de Serviço'),ano),locFolder=obterOuCriarPasta_(base,String(os.LocacaoID)),pasta=obterOuCriarPasta_(locFolder,os.Numero);let assinaturaId='';
  fotos.forEach((f,i)=>{const blob=base64ParaBlob_(f,'foto-'+(i+1)+'.jpg');const arq=pasta.createFile(blob);registrarArquivoOS_(os.ID,'Foto',arq);});
  const assinatura=pasta.createFile(base64ParaBlob_(assinaturaBase64,'assinatura.png'));assinaturaId=assinatura.getId();registrarArquivoOS_(os.ID,'Assinatura',assinatura);return {assinaturaId:assinaturaId};
}
function base64ParaBlob_(data,nome){const m=String(data).match(/^data:([^;]+);base64,(.+)$/);if(!m)throw new Error('Arquivo em formato inválido.');const bytes=Utilities.base64Decode(m[2]);if(bytes.length>6*1024*1024)throw new Error('Arquivo excede 6 MB.');return Utilities.newBlob(bytes,m[1],nome);}
function registrarArquivoOS_(osId,tipo,arquivo){inserir_('ArquivosOS',{ID:uuid_(),OSID:osId,Tipo:tipo,ArquivoID:arquivo.getId(),Nome:arquivo.getName(),MimeType:arquivo.getBlob().getContentType(),Tamanho:arquivo.getSize(),CriadoEm:agora_(),CriadoPor:emailAtual_()});}

function gerarPdfOS(osId){
  const os=validarOsDoMotorista_(osId);if(os.Status!==APP.OS.CONCLUIDA)throw new Error('Conclua a OS antes de gerar o PDF.');const loc=buscarPor_('Locacoes','ID',os.LocacaoID),cli=buscarPor_('Clientes','ID',os.ClienteID),itens=tabela_('OSItens').filter(i=>String(i.OSID)===String(os.ID));
  const doc=DocumentApp.create('Temporário '+os.Numero),b=doc.getBody(),cfg=configuracoes_();b.appendParagraph(cfg.NOME_EMPRESA||APP.NOME).setHeading(DocumentApp.ParagraphHeading.HEADING1);b.appendParagraph('ORDEM DE SERVIÇO '+os.Numero).setHeading(DocumentApp.ParagraphHeading.HEADING2);b.appendParagraph('Tipo: '+os.Tipo+' | Status: '+os.Status);b.appendParagraph('Cliente: '+(cli?.NomeRazao||''));b.appendParagraph('Endereço: '+os.EnderecoSnapshot);b.appendParagraph('Motorista: '+(buscarPor_('Motoristas','ID',os.MotoristaID)?.Nome||''));b.appendParagraph('Caminhão/placa: '+(buscarPor_('Caminhoes','ID',os.CaminhaoID)?.Placa||''));b.appendParagraph('Caçambas: '+itens.map(i=>buscarPor_('Cacambas','ID',i.CacambaID)?.Numero).join(', '));b.appendParagraph('Conclusão: '+os.ConclusaoEm);b.appendParagraph('Responsável: '+os.NomeSignatario);b.appendParagraph('Observações: '+(os.Observacoes||''));
  const arquivos=tabela_('ArquivosOS').filter(a=>String(a.OSID)===String(os.ID));arquivos.filter(a=>a.Tipo==='Foto').slice(0,4).forEach(a=>{try{b.appendImage(DriveApp.getFileById(a.ArquivoID).getBlob()).setWidth(280);}catch(e){}});if(os.AssinaturaArquivoID)try{b.appendParagraph('Assinatura:');b.appendImage(DriveApp.getFileById(os.AssinaturaArquivoID).getBlob()).setWidth(220);}catch(e){}
  doc.saveAndClose();const pdf=DriveApp.getFileById(doc.getId()).getAs(MimeType.PDF).setName(os.Numero+'.pdf'),pasta=obterOuCriarPasta_(obterOuCriarPasta_(pastaRaiz_(),'Ordens de Serviço'),String(new Date().getFullYear())),arquivo=pasta.createFile(pdf);DriveApp.getFileById(doc.getId()).setTrashed(true);atualizarPorId_('OrdensServico',os.ID,{PdfArquivoID:arquivo.getId(),AtualizadoEm:agora_()});registrarArquivoOS_(os.ID,'PDF',arquivo);return {arquivoId:arquivo.getId(),nome:arquivo.getName(),url:arquivo.getUrl()};
}
